---
title: "wbone-results"
author: "Harpo Maxx"
date: "28/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Brief analisys of Robert data
Analysis of the first results of the NN provided by Robert From WB

```{r}
library(dplyr)
library(ggplot2)
library(urltools)
wdata=read.csv(file = "/home/harpo/Dropbox/ongoing-work/dga/data/2017-02-27-dnsdga.csv",header = T)
worbased=c('dga.banjori', 'dga.suppobox', 'dga.volatile', 'dga.matsnu', 'dga.beebone', 'dga.madmax', 'dga.cryptowall')

# exctract TLD as-is.

tld=tld_extract(wdata$domain)
wdata$tld=tld$tld
wdata %>% group_by(class) %>% summarise(percent=n()/nrow(wdata))

wdata$tld
```

```{r}
# Probability distribution of .cz domains
wdata %>% filter(class==1 & grepl("\\.cz",domain)) %>% arrange(desc(probability))

# mean and sd probabilty for all the tld classified as DGA in data.
wdata %>% filter(class==1) %>% group_by(tld) %>% summarise(mean=mean(probability),sd=sd(probability))

# 
wdata %>% filter(grepl("cz", tld))  %>% group_by(class) %>% summarise(n=n()) %>%mutate(percent = n / sum(n))
```


```{r}
prob_all=wdata %>% group_by(tld) %>% summarise(avg_prob=mean(probability),sd_prob=sd(probability))
dga=wdata %>% filter(class==1) %>% group_by(tld) %>% summarise(dga=n())
legit=wdata %>% filter(class==0) %>% group_by(tld) %>% summarise(legit=n())

dga_freq=inner_join(dga,legit,by="tld")%>% mutate(percent=dga/(dga+legit))
dga_freq=inner_join(dga_freq,prob_all,by="tld")
dga_freq=dga_freq  %>% filter((dga+legit)>10)
dga_freq
```

```{r}
library(plotly)
ggplot()+
  geom_point(data=dga_freq,aes(x=tld,y=percent,size=(dga+legit),
                               text = paste0("tot freq:", (dga+legit),
                                             "<BR>avg prob:", (avg_prob),
                                             "<BR>sd prob:", (sd_prob)
                                             )),colour='blue')+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
   xlab('pseudo-tld domains' )+ylab("DGA percentage/proportion")+
   ggtitle("DGA vs Legit Proportion on 7hs of WB data ")

ggplotly()
```



## Results from testset (NN)

```{r}
library(caret)
library(plotly)
nntest=read.csv(file = "/home/harpo/Dropbox/ongoing-work/git-repos/dga-wb/test_edna_model_full.csv.gz",header = T)

nntest=nntest %>% mutate(predicted_class=ifelse(predicted_probability>0.90,1,0))
nntest=nntest %>% mutate(label=tolower(label))

recall=nntest %>% group_by(label) %>% summarise(recall=sum(predicted_class==class)/n(),support=n()) 
precision_far=nntest %>% group_by(label) %>% summarise(precision=1-(sum(predicted_class!=class)/n()),support=n()) 

recall=recall %>% mutate(class=ifelse(grepl('dga',label),1,0))

recall=recall %>% filter( label %in% worbased)
#confusionMatrix(nntest$predicted_class,nntest$class)

ggplot()+
  geom_point(data=recall,aes(x=label,y=recall,size=support,colour=class))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_color_gradient2(low = "cyan", mid='blue',high = "red")+
   xlab('Types' )+ylab("Recall")+
   guides(colour=FALSE,size=FALSE)
ggplotly()

```
```{r, fig.height=2, fig.width=8}
require(scales)

fp=nntest %>% filter(class == 1)
charlist=unlist(sapply(fp$sample, function(x) c(str_split(x,"")[1])))

freq_char_dga=ggplot(data.frame(charlist),aes(x=charlist))+
   geom_bar(col="black",fill='white',aes(y = (..count..)/sum(..count..)))+
  scale_y_continuous(labels=percent,limits=c(0,0.1))+ylab("Percent")+xlab("DGA domains")+
#  ggtitle("Character Frequency Distribution for DGA domains")+
  theme_bw()
nrow(nntest)
```

```{r, fig.height=2, fig.width=8}

normal=nntest %>% filter(class == 0)
charlist_normal=unlist(sapply(normal$sample, function(x) c(str_split(x,"")[1])))


freq_char_legit=ggplot(data.frame(charlist_normal),aes(x=charlist_normal))+
   geom_bar(col="black",fill='white',aes(y = (..count..)/sum(..count..)))+
  scale_y_continuous(labels=percent)+ylab("Percent")+xlab("Legit domains")+
 # ggtitle("Character Frequency Distribution for Legit domains")+
  theme_bw()
```
```{r, fig.height=4, fig.width=10}
library(grid)
library(gridExtra)
grid.arrange(freq_char_dga, freq_char_legit, nrow = 2, ncol=1)
```

```{r}
class_dga=nntest %>% filter(class == 1)

# calculate Char freq by DGA type
charlist_by_type=class_dga  %>% group_by(label) %>% do(charlist= unlist(sapply(.$sample, function(x) c(str_split(x,"")[1]))))
save(charlist_by_type,file="./robjs/charlist_by_type.Rda")

dga_type=as.vector(unlist(charlist_by_type %>% filter(label=="DGA.suppobox") %>% select(charlist)))

ggplot(data.frame(charlist=dga_type),aes(x=charlist))+
   geom_bar(col="skyblue",fill='orange',aes(y = (..count..)/sum(..count..)))+
  scale_y_continuous(labels=percent)+ylab("Percent")+xlab("Domains")+
 # ggtitle("Character Frequency Distribution for Legit domains")+
  theme_bw()

```

```{r, fig.height=12, fig.width=12}
P<-list()
for (l in charlist_by_type$label[1:55]){
  print(l)
  dga_type=as.vector(unlist(charlist_by_type %>% filter(label==l) %>% select(charlist)))

  p<-ggplot(data.frame(charlist=dga_type),aes(x=charlist))+
    geom_bar(col="black",fill='white',aes(y = (..count..)/sum(..count..)))+
    scale_y_continuous(labels=percent)+ylab("Percent")+xlab("")+
    ggtitle(l)+
    theme(plot.title = element_text(size = 5))+
    theme_bw()
  P<-c(P,list(p))
}
do.call(grid.arrange,c(P,ncol=5))
```


```{r freq_char_wordbased, fig.height=12}

# calculate Char freq by DGA type
charlist_by_type_wb=class_dga  %>% filter (label %in% worbased) %>% group_by(label) %>% do(charlist= unlist(sapply(.$sample, function(x) c(str_split(x,"")[1]))))
save(charlist_by_type_wb,file="./robjs/charlist_by_type_wb.Rda")
P<-list()
for (l in charlist_by_type_wb$label){
  print(l)
  dga_type=as.vector(unlist(charlist_by_type_wb %>% filter(label==l) %>% select(charlist)))

  p<-ggplot(data.frame(charlist=dga_type),aes(x=charlist))+
    geom_bar(col="black",fill='white',aes(y = (..count..)/sum(..count..)))+
    scale_y_continuous(labels=percent)+ylab("Percent")+xlab("")+
    ggtitle(l)+
    theme(plot.title = element_text(size = 5))+
    theme_bw()
  P<-c(P,list(p))
}
do.call(grid.arrange,c(P,ncol=3))

```
